### ISSUE TITLE
Detection outputs must ignore model configuration files

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#122]
In my test with one input file, mic is constantly adding it as an output file after the execution, which is not correct.

**Comment by dgarijo** [comment]
Example:
```bash
Running
 ./run   -i1 config.yml  -p1 Subsidy
b'+ python3 ./export_mc.py\n'
b'Skipping: SoftwareImage\n'
b'Parameter has been processed\n'
b'DatasetSpecification has been processed\n'
b'Traceback (most recent call last):\n'
b'  File "./export_mc.py", line 118, in <module>\n'
b"    import_script(onto['url'], onto['exclude'], graph_url, query_url, cfg['instance_uri_prefix'], graph_path, cfg['useLabel'])\n"
b'  File "./export_mc.py", line 95, in import_script\n'
b'    csvwriter.writerow(temp)\n'
b"UnicodeEncodeError: 'ascii' codec can't encode character '\\u2013' in position 380: ordinal not in range(128)\n"
Success
The model has generated the following files
config.yml
catalog_export/mint@isi.edu/Parameter.csv
catalog_export/mint@isi.edu/DatasetSpecification.csv
catalog_export/mint@isi.edu/VariablePresentation.csv
Added: config_yml as a output
Added: catalog_exportmintisi_eduparameter_csv as a output
Added: catalog_exportmintisi_edudatasetspecification_csv as a output
Added: catalog_exportmintisi_eduvariablepresentation_csv as a output
```
config_yml is added as output. It was categorized already as an input in mic.yaml, and as a configuration file.

**Comment by dgarijo** [comment]
Oh, and I know the script shows an error, which is due to windows encoding. It's independent of mic
