### ISSUE TITLE
Remove add models, modelversions and model configurations

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mic#128]
I have some concerns about the following commands

```
mic model 
mic modelconfiguration
```

I think it is not working well because we don't have the time to maintain or test these commands.
What are we going to do?
I would remove the features and send the users to the model catalog.

If not, who is going to work on it?

**Comment by sirspock** [comment]
@dgarijo

**Comment by dgarijo** [comment]
Let's remove model configuration. Let's leave model for now because it works, even if it's simplified.

**Comment by Cmheidelberg** [comment]
Should this be closed now?

**Comment by sirspock** [comment]
I propose delete model too. It doesn't make sense to support it.  There many bugs, Hernan is releasing a better interface and we don't have the time to work on it.

**Comment by dgarijo** [comment]
I agree in principle, but it's a requirement to still maintain this right now. 

We can keep a minimal amount of metadata to minimize bugs (like keeping only text-based values).

**Comment by sirspock** [comment]
I think the best option is:
```
$ mic model add 
Name:
Description:
Category:

To add more metadata go to: ....
```

**Comment by sirspock** [comment]
By now we should delete it. *It is not working well*

**Comment by sirspock** [comment]
I tested 

```
~/repos/mic on release_v1.5.0 !1 ❯ mic model add -p mosorio                                                                                                             took 7s
WARNING: You are using mic version 0.4.4, however version 1.0.0 is available.
You should consider upgrading via the 'pip install --upgrade mic' command.
======= Model ======
The actual values are:
+-------+----------------+---------+
|   no. | Property       | Value   |
+=======+================+=========+
|     1 | Name           |         |
+-------+----------------+---------+
|     2 | Description    |         |
+-------+----------------+---------+
|     3 | Keywords       |         |
+-------+----------------+---------+
|     4 | Website        |         |
+-------+----------------+---------+
|     5 | Documentation  |         |
+-------+----------------+---------+
|     6 | Versions       |         |
+-------+----------------+---------+
|     7 | Author         |         |
+-------+----------------+---------+
|     8 | Contributor    |         |
+-------+----------------+---------+
|     9 | Contact person |         |
+-------+----------------+---------+
|    10 | License        |         |
+-------+----------------+---------+
|    11 | Category       |         |
+-------+----------------+---------+
|    12 | Creation date  |         |
+-------+----------------+---------+
|    13 | Assumptions    |         |
+-------+----------------+---------+
|    14 | Download URL   |         |
+-------+----------------+---------+
|    15 | Logo           |         |
+-------+----------------+---------+
|    16 | Purpose        |         |
+-------+----------------+---------+
|    17 | Citation       |         |
+-------+----------------+---------+
Select the property to edit [1-17] or ['show', 'save', 'send', 'exit'] [1]: 1
No value for Name
Definition: Name of the model
Model - Name : adsfasd
======= Model ======
The actual values are:
+-------+----------------+-------------+
|   no. | Property       | Value       |
+=======+================+=============+
|     1 | Name           | ['adsfasd'] |
+-------+----------------+-------------+
|     2 | Description    |             |
+-------+----------------+-------------+
|     3 | Keywords       |             |
+-------+----------------+-------------+
|     4 | Website        |             |
+-------+----------------+-------------+
|     5 | Documentation  |             |
+-------+----------------+-------------+
|     6 | Versions       |             |
+-------+----------------+-------------+
|     7 | Author         |             |
+-------+----------------+-------------+
|     8 | Contributor    |             |
+-------+----------------+-------------+
|     9 | Contact person |             |
+-------+----------------+-------------+
|    10 | License        |             |
+-------+----------------+-------------+
|    11 | Category       |             |
+-------+----------------+-------------+
|    12 | Creation date  |             |
+-------+----------------+-------------+
|    13 | Assumptions    |             |
+-------+----------------+-------------+
|    14 | Download URL   |             |
+-------+----------------+-------------+
|    15 | Logo           |             |
+-------+----------------+-------------+
|    16 | Purpose        |             |
+-------+----------------+-------------+
|    17 | Citation       |             |
+-------+----------------+-------------+
Select the property to edit [1-17] or ['show', 'save', 'send', 'exit'] [1]: 9
No value for Contact person
Select action: (select, add) [select]: select
Available resources
Traceback (most recent call last):
  File "/Users/mosorio/.pyenv/versions/3.7.6/bin/mic", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "/Users/mosorio/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mosorio/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mosorio/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mosorio/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mosorio/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mosorio/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mosorio/repos/mic/src/mic/__main__.py", line 108, in add
    create_model(profile=profile)
  File "/Users/mosorio/repos/mic/src/mic/resources/model.py", line 20, in create
    call_menu_select_property(mapping_model, ModelCli(profile), request)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 330, in call_menu_select_property
    resource_object=resource_object, mapping=mapping)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 249, in call_ask_value
    menu_call_actions_complex(request, variable_selected, resource_name, mapping, resource_object, request_property)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 106, in menu_call_actions_complex
    call_menu_select_existing_resources(request, variable_selected, resource_object, mapping, request_property)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 294, in call_menu_select_existing_resources
    select_sub_resource = menu_select_existing_resources(resource_object, request_property, variable_selected)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 25, in menu_select_existing_resources
    response = sub_resource.get()
TypeError: get() missing 1 required positional argument: 'self'
```

**Comment by sirspock** [comment]
Both tests returns errors!

**Comment by sirspock** [comment]
Also, the creation of model and model versions are included by the publish step

**Comment by dgarijo** [comment]
Ok, let's remove this for the moment then (do not forget to update the doc too)
