### ISSUE TITLE
When I try mic in my docker image (prepared by mic) I get an error

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#156]
How to reproduce:
`mic encapsulate start`
select python3. After image starts:
```
root@4b61dfc7fdd9:/tmp/mint# mic --help
Traceback (most recent call last):
  File "/usr/local/bin/mic", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

**Comment by dgarijo** [comment]
Doing `export LC_ALL=C.UTF-8` fixes the issue, but it should not happen in the first place.

**Comment by dgarijo** [comment]
This has been fixed in the latest commits
