### ISSUE TITLE
mic encapsulate trace fails

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#157]
In the docker image created by mic, I typed the following and got an error:
```
root@4b61dfc7fdd9:/tmp/mint# mic encapsulate trace
Traceback (most recent call last):
  File "/usr/local/bin/mic", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/src/mic/src/mic/click_encapsulate/commands.py", line 96, in trace
    import reprozip.tracer.trace
ModuleNotFoundError: No module named 'reprozip'
```

**Comment by dgarijo** [comment]
After figuring out that I should have typed the command, then I executed my script, but still got an error:
```
root@0211e411588b:/tmp/mint# mic encapsulate trace export_mc.py --overwrite
2020-06-16 03:58:38,706 reprozip     INFO     Removing existing trace directory .reprozip-trace
2020-06-16 03:58:38,765 reprozip     INFO     Running program
2020-06-16 03:58:38,767 reprozip     INFO     child created, pid=71
2020-06-16 03:58:38,767 reprozip     CRITICAL couldn't use ptrace: Operation not permitted
This could be caused by a security policy or isolation mechanism (such as Docker), see http://bit.ly/2bZd8Fa
2020-06-16 03:58:38,772 reprozip     INFO     process 71 created by initial fork()
2020-06-16 03:58:38,773 reprozip     INFO     [71] process exited (code 125), 0 processes remain
2020-06-16 03:58:38,799 reprozip     WARNING  Program exited with non-zero code 125
2020-06-16 03:58:38,800 reprozip     INFO     Program completed
2020-06-16 03:58:38,813 reprozip     INFO     Running filter plugin builtin
2020-06-16 03:58:38,814 reprozip     INFO     Running filter plugin python
2020-06-16 03:58:38,818 reprozip     INFO     Identifying Debian packages for 3 files...
2020-06-16 03:58:38,862 reprozip     INFO     1 packages with 1 files, and 2 other files
```

**Comment by dgarijo** [comment]
I was able to successfully execute this step
