### ISSUE TITLE
Selecting python3.8 fails

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#159]
When I start, if I select python3.8 I will get the following error:
```
Select a option  (python3.7, python3.8, conda4.7.12): python3.8
Dockerfile has been created: /nas/home/dgarijo/testMIC/mic/docker/Dockerfile
Downloading the base image and building your image
Traceback (most recent call last):
  File "/nas/home/dgarijo/mic/env/bin/mic", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nas/home/dgarijo/mic/src/mic/click_encapsulate/commands.py", line 68, in start
    image = build_docker(mic_dir / DOCKER_DIR, name)
  File "/nas/home/dgarijo/mic/src/mic/component/executor.py", line 100, in build_docker
    image, logs = client.images.build(path=str(docker_path), tag="{}".format(name), nocache=True)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: manifest for mintproject/python:38 not found: manifest unknown: manifest unknown
```

**Comment by dgarijo** [comment]
When I select `conda4.7.12` I get another error:
```
conda4.7.12
Traceback (most recent call last):
  File "/nas/home/dgarijo/mic/env/bin/mic", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nas/home/dgarijo/mic/env/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nas/home/dgarijo/mic/src/mic/click_encapsulate/commands.py", line 67, in start
    detect_framework_main(user_execution_directory)
  File "/nas/home/dgarijo/mic/src/mic/component/detect.py", line 68, in detect_framework_main
    conda_freeze(requirements_file)
  File "/nas/home/dgarijo/mic/src/mic/component/conda.py", line 7, in freeze
    reqs = subprocess.check_output(['conda', 'env', 'export', '--from-history'])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'
```
I think MIC is expecting a folder that I don't have. Note that I am just selecting an execution environment, the system never asked in my component was a conda component.

**Comment by dgarijo** [comment]
The python3.8 error is gone after the newest commits.

**Comment by dgarijo** [comment]
Actually it still fails, unfortunately:
```bash
Select a option  (python3.7, python3.8, conda4.7.12): python3.8
Dockerfile has been created: C:\Users\dgarijo\Desktop\mic_test_python\mic\docker\Dockerfile
Downloading the base image and building your image
Traceback (most recent call last):
  File "C:\Users\dgarijo\Documents\GitHub\mic\Scripts\mic-script.py", line 33, in <module>
    sys.exit(load_entry_point('mic==0.4.4', 'console_scripts', 'mic')())
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\mic\click_encapsulate\commands.py", line 69, in start
    image = build_docker(mic_dir / DOCKER_DIR, name)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\mic\publisher\docker.py", line 32, in build_docker
    image, logs = client.images.build(path=str(docker_path), tag="{}".format(name), nocache=True)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\docker\models\images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: ADD failed: stat /var/lib/docker/tmp/docker-builder449073109/requirements.txt: no such file or directory
```

**Comment by sirspock** [comment]
Are you using the option dependencies/no-dependecies?
The information is not complete.

**Comment by dgarijo** [comment]
Full log:
```bash
(mic) PS C:\Users\dgarijo\Desktop\mic_test_python> mic encapsulate start
Model Configuration name: test_python
The directory mic already exists. If you continue, you can lost a previous component
Do you want to continue? [Y/n]: Y
WARNING: Git directory
MIC has initialized the component.
[Created] data:      C:\Users\dgarijo\Desktop\mic_test_python\mic\data
[Created] docker:    C:\Users\dgarijo\Desktop\mic_test_python\mic\docker
[Created] src:       C:\Users\dgarijo\Desktop\mic_test_python\mic\src
[Created] mic.yaml:  C:\Users\dgarijo\Desktop\mic_test_python\mic\mic.yaml
C:\Users\dgarijo\Desktop\mic_test_python\mic\mic.yaml created
You can disable the detection of dependencies using the option --no-dependencies
MIC has detect 3 possible framework/language on component: python3.7,python3.8,conda4.7.12
Please select the correct option
This information allows MIC to select the correct Docker Image
Select a option  (python3.7, python3.8, conda4.7.12): python3.8
Dockerfile has been created: C:\Users\dgarijo\Desktop\mic_test_python\mic\docker\Dockerfile
Downloading the base image and building your image
Traceback (most recent call last):
  File "C:\Users\dgarijo\Documents\GitHub\mic\Scripts\mic-script.py", line 33, in <module>
    sys.exit(load_entry_point('mic==0.4.4', 'console_scripts', 'mic')())
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\mic\click_encapsulate\commands.py", line 69, in start
    image = build_docker(mic_dir / DOCKER_DIR, name)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\mic\publisher\docker.py", line 32, in build_docker
    image, logs = client.images.build(path=str(docker_path), tag="{}".format(name), nocache=True)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\docker\models\images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: ADD failed: stat /var/lib/docker/tmp/docker-builder449073109/requirements.txt: no such file or directory
```

**Comment by dgarijo** [comment]
In case it's needed, this is the script I am testing on
[mic_test_python.zip](https://github.com/mintproject/mic/files/4795438/mic_test_python.zip)

**Comment by sirspock** [comment]
Fixed. Please remember to upgrade the package. The previous outputs are from an old version

**Comment by dgarijo** [comment]
I will (I updated earlier today)
