### ISSUE TITLE
Publish a new version of component fails (when repository exists)

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#216]
**Describe bug**:
I tried to publish a component that already exists. I get the following error:

```
(mic) PS C:\Users\dgarijo\Desktop\192\java_model> mic encapsulate publish
Automatically found mic.yaml in C:\Users\dgarijo\Desktop\192\java_model\mic\mic.yaml
This step publishes your code, DockerImage and ModelConfiguration
Creating the git repository
Compressing your code
Creating a new commit
Creating or using the GitHub repository
The git repository has a remote server configured https://github.com/dgarijo/test_192.git
Creating a new version
Previous version 20.6.1
New version: 20.6.2
Pushing your changes to the server
Traceback (most recent call last):
  File "C:\Users\dgarijo\Documents\GitHub\mic\Scripts\mic-script.py", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\mic\src\mic\click_encapsulate\commands.py", line 530, in publish
    push(mic_config_path.parent, mic_config_path, name, profile)
  File "c:\users\dgarijo\documents\github\mic\src\mic\publisher\github.py", line 36, in push
    git_push(repo, profile, _version)
  File "c:\users\dgarijo\documents\github\mic\src\mic\publisher\github.py", line 121, in git_push
    remote.push(['refs/heads/master'], callbacks=callbacks)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\pygit2\remote.py", line 224, in push
    payload.check_error(err)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\pygit2\callbacks.py", line 93, in check_error
    check_error(error_code)
  File "c:\users\dgarijo\documents\github\mic\lib\site-packages\pygit2\errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
```

**Comment by sirspock** [comment]
The problem is:
```
_pygit2.GitError: cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
```

**Comment by sirspock** [comment]
I'm going to add a pull method and try to handle the conflicts.

**Comment by dgarijo** [comment]
I saw you did a fix in develop. Is this problem fixed?

**Comment by sirspock** [comment]
It's fixed
