### ISSUE TITLE
Add push

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#28]
**Describe the bug**
In the latest version, my credentials are ok (I have mosorio's graph), and I can show data fine. But my entries are not being pushed

**To Reproduce**
Edit a model, select send, the wizard says success and exit. But my model entry is not created.

**Comment by sirspock** [comment]
Push is not implemented

**Comment by sirspock** [comment]
Use `send` in a subresource fails

```
Select action: (select, add) [select]: add
======= ModelVersion Version ======
The actual values are:
+-------+----------------------+---------+
|   no. | Property             | Value   |
+=======+======================+=========+
|     1 | Name                 |         |
+-------+----------------------+---------+
|     2 | Description          |         |
+-------+----------------------+---------+
|     3 | Version number       |         |
+-------+----------------------+---------+
|     4 | Model Configurations |         |
+-------+----------------------+---------+
Select the property to edit [1-4] or ['show', 'save', 'send', 'exit'] [1]: send
Traceback (most recent call last):
  File "/Users/mosorio/.pyenv/versions/mic/bin/mic", line 11, in <module>
    load_entry_point('mic', 'console_scripts', 'mic')()
  File "/Users/mosorio/.pyenv/versions/3.7.6/envs/mic/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mosorio/.pyenv/versions/3.7.6/envs/mic/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mosorio/.pyenv/versions/3.7.6/envs/mic/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mosorio/.pyenv/versions/3.7.6/envs/mic/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mosorio/.pyenv/versions/3.7.6/envs/mic/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mosorio/.pyenv/versions/3.7.6/envs/mic/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mosorio/repos/mic/src/mic/__main__.py", line 82, in add
    create_model()
  File "/Users/mosorio/repos/mic/src/mic/resources/_model.py", line 16, in create
    call_menu_select_property(mapping_model, ModelCli(), request)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 269, in call_menu_select_property
    resource_object=resource_object, mapping=mapping)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 192, in call_ask_value
    menu_call_actions_complex(request, variable_selected, resource_name, mapping, resource_object, request_property)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 94, in menu_call_actions_complex
    mapping_create_value_complex(request, variable_selected, mapping, request_property)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 325, in mapping_create_value_complex
    value = mapping_resource_complex(variable_selected, mapping, request)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 310, in mapping_resource_complex
    return call_menu_select_property(sub_resource_mapping, sub_resource, full_request)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 264, in call_menu_select_property
    if handle_actions(request, property_chosen, mapping, resource_object, full_request=full_request):
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 364, in handle_actions
    url = menu_push(full_request, resource_object)
  File "/Users/mosorio/repos/mic/src/mic/_menu.py", line 143, in menu_push
    return resource_object.post(request)
AttributeError: type object 'SoftwareVersionCli' has no attribute 'post'
```
