### ISSUE TITLE
Cannot create SWAT component

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#301]
I was attempting to create a SWAT component with Timo. However, mic failed in the `mic pkg inputs` command.
Here is the component: https://www.dropbox.com/s/411vz59l9kbfgua/naryn_swat2.7z?dl=0 (too big for GitHub).

**Comment by mosoriob** [comment]
```bash
mic   commands.py        ERROR    Inputs failed: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mic/click_encapsulate/commands.py", line 412, in inputs
    code_files = find_code_files(spec, inputs_reprozip, config_files_list, user_execution_directory)
  File "/usr/local/lib/python3.6/dist-packages/mic/component/reprozip.py", line 283, in find_code_files
    if is_executable(files_path):
  File "/usr/local/lib/python3.6/dist-packages/mic/component/reprozip.py", line 293, in is_executable
    name = "." + (name.split("."))[1]
IndexError: list index out of range
```

**Comment by mosoriob** [comment]
The code is assuming an extension in the file.

```python
    for i in EXECUTABLE_EXTENSIONS:
        name = file_path.name.lower()
        name = "." + (name.split("."))[1]
        if i.lower() == name.lower():
            return True
```

**Comment by mosoriob** [comment]
The recommendation is to use the Path module and not use strings operation.

`Path('/root/dir/sub/file.ext').stem`


```

PurePath.stem

    The final path component, without its suffix:
    >>>

    >>> PurePosixPath('my/library.tar.gz').stem
    'library.tar'
    >>> PurePosixPath('my/library.tar').stem
    'library'
    >>> PurePosixPath('my/library').stem
    'library'
```

**Comment by dgarijo** [comment]
@mosoriob do you think this is a fix @Cmheidelberg can easily do? I think we should have this ready before our next meeting with Timo next Wednesday

**Comment by dgarijo** [comment]
I was able to successfully finish the swat component, so I will close this issue
